global using HireMind.Domain;
global using HireMind.Domain.Dtos.BusinessCard;
global using HireMind.Domain.Dtos.ManageJobs;
global using HireMind.Domain.Dtos.SharedDtos;
global using HireMind.Domain.IRepositories;
global using HireMind.Domain.SeedWork;
global using HireMind.Infrastructure.SeedWork;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.Extensions.DependencyInjection;
global using HireMind.Application.Interfaces;
global using HireMind.Domain.Entities.Security;
global using RoleModel = HireMind.Domain.Entities.Security.Role;
